### ISSUE TITLE
SELinux Errors

### ISSUE THREAD

**Issue by Mimoja** [RTAndroid/android_packages_apps_Ballsort#12]
avc: denied { write } for pid=4423 comm="ndroid.ballsort" name="value" dev="sysfs" ino=20472 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1

**Comment by Mimoja** [comment]
<38>[  197.598675] [c0] type=1400 audit(1357000631.355:117): avc: denied { write } for pid=6771 comm="Ballsort_Feeder" path="/dev/i2c-10" dev="tmpfs" ino=136 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
<38>[  197.912349] [c0] type=1400 audit(1357000631.665:118): avc: denied { read } for pid=6771 comm="Ballsort_Feeder" path="/dev/i2c-10" dev="tmpfs" ino=136 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1

**Comment by ikalkov** [comment]
To fix those on the system level, we would need to allow user applications to access /sys and /dev, which is a huge security hole. I don't think it is a good idea.
