### ISSUE TITLE
Vorbereitung auf RWTH-transparent

### ISSUE THREAD

**Issue by ikalkov** [RTAndroid/android_packages_apps_Ballsort#14]
Sammelticket für alle zugehörigen Aufgaben:

1. Kompressor leeren? Max sagt, dass sich dort drin ggf. Wasser angesammelt hat. David hat das schon mal gemacht.

2. Eine geeignete Plastikbox für den ODROID finden, Kabel verlegen und die Box über oder neben der Spannungsversorgung platzieren.

3. Materialliste erstellen was alles hin und her transportiert werden muss.

4. Die Anlage mit einem Ersatz-ODROID testen?

**Comment by ikalkov** [comment]
5. Jemanden mit einem Auto finden, der die Anlage hin- und zurückfährt

6. Flyer mitnehmen

**Comment by Mimoja** [comment]
5. Wann muss gefahren werden?
