### ISSUE TITLE
Don't add the color if it wasn't detected falling

### ISSUE THREAD

**Issue by ikalkov** [RTAndroid/android_packages_apps_Ballsort#5]
Method getNextColumn() has a side effect: it saves the color to the pattern. This may cause issues if the ball will get stuck in the feeder.

We should extract the pattern filling logic into a separate method. It will be called with the expected color and calculated column only after the ball is detected falling. The column should be checked additionally. The method getNextColumn() just retrieves the next column without saving it.

**Comment by Mimoja** [comment]
On it

**Comment by Mimoja** [comment]
Done

**Comment by ikalkov** [comment]
@Mimoja 
1) There are "Assignees" to mark YOU are working on this
2) I don't see a single commit - what exactly is "done"?
3) The ticket should be closed, if everything is finished

**Comment by Mimoja** [comment]
1) And how can i assign something?
2) I can't push from the machine at the chair. Dont know what is wrong there. It does not take my ssh keys for signing. You have to push i guess. Else: As i dont not have ANY rights at this Repository the GUI work is done on my fork...
3) how?

**Comment by ikalkov** [comment]
You should have rights on this repository, as you are member of the organization. It works for other members at least. Find a way.
1) If you are working on your own fork, (1) can be ignored.
2) Push via HTTPS? Pull request? 
3) Merge requests with "Fixes #X" commits.

**Comment by Mimoja** [comment]
Implemented on local computer. Merge on monday
